version = 0.1
[default.deploy.parameters]
stack_name = "bia-serverless"
resolve_s3 = true
s3_prefix = "bia-serverless"
region = "us-east-1"
profile = "bia-serverless"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
